use_frameworks!

target 'NMTransitionDeinitExtension_Example' do
  pod 'NMTransitionDeinitExtension', :path => '../'

  target 'NMTransitionDeinitExtension_Tests' do
    inherit! :search_paths

    
  end
end
